apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  mysql_host: mysql-profile-management
  mysql_database: profile_management
  mongodb_product_host: mongodb-product-catalog
  mongodb_contact_host: mongodb-contact-support
  mongodb_contact_database: contact_support
  postgres_host: postgres-product-inventory
  postgres_database: product_inventory
  product_inventory_api: http://product-inventory:3002
  product_catalog_api: http://product-catalog:3001
  shipping_api: http://shipping-and-handling:8080
  order_mongodb_uri: mongodb://mongodb-order-management:27017/order_management
