apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  mysql_root_password: root_password
  mysql_user: profile_user
  mysql_password: profile_password
  postgres_user: inventory_user
  postgres_password: inventory_password
