[ecommerce]
# Replace this IP with terraform output instance_public_ip after terraform apply.
ecommerce-server ansible_host=YOUR_EC2_PUBLIC_IP ansible_user=ubuntu ansible_ssh_private_key_file=../terraform_infra/ecommerce-deployer.pem
