---
- name: Configure and deploy ecommerce microservices stack
  hosts: ecommerce
  become: true
  vars:
    app_dir: /opt/ecommerce-microservices
    compose_file: docker-compose.yml
    repo_url: https://github.com/andronousss/final-project.git

  roles:
    - docker
    - deploy
    - monitoring
